name: "Auto-Reformat Markdown with Gemini AI"

on:
  push:
    paths:
      - "**/*.md"           # only trigger if any Markdown file changes
    branches:
      - main               # or whichever branch you want this to run on

permissions:
  contents: write         # so that the action can push commits back

jobs:
  reformat_markdown:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository, full history so we can diff HEAD^ vs HEAD
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      # <– required so we can see HEAD^ in git diff

      # 2) Set up Python (if not already)
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3) Install necessary Python dependencies
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4) Run our reformatter script
      - name: "Reformat changed Markdown via Gemini"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF:     ${{ github.ref }}
        run: |
          chmod +x .github/scripts/format_markdown.py
          python .github/scripts/format_markdown.py
