name: "Auto-Reformat Markdown with Gemini AI"

on:
  push:
    paths:
      - "**/*.md"
    branches:
      - main

permissions:
  contents: write

jobs:
  reformat_markdown:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: "Reformat changed Markdown via Gemini"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF:     ${{ github.ref }}
        run: |
          chmod +x .github/scripts/format_markdown.py
          python .github/scripts/format_markdown.py
